# Generated by Django 4.2 on 2024-06-09 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('cancel', 'отмена публикации'),), 'verbose_name': 'пользователь', 'verbose_name_plural': 'пользователи'},
        ),
    ]
