# Generated by Django 4.2 on 2024-06-15 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('user_activ', 'Блокировка пользователя'),), 'verbose_name': 'пользователь', 'verbose_name_plural': 'пользователи'},
        ),
    ]
