# Generated by Django 4.2 on 2024-06-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_alter_mailingletters_end_alter_mailingletters_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingletters',
            name='start',
            field=models.DateTimeField(auto_now_add=True, verbose_name='начало рассылки'),
        ),
    ]
