# Generated by Django 4.2 on 2024-06-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_client_owner'),
        ('mailing', '0004_alter_mailingletters_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingletters',
            name='clients',
            field=models.ManyToManyField(blank=True, null=True, related_name='settings', to='client.client'),
        ),
    ]
