# Generated by Django 4.2 on 2024-05-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=500, null=True, verbose_name='тема письма')),
                ('body', models.CharField(blank=True, null=True, verbose_name='тема письма')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='дата записи')),
                ('updated_at', models.DateField(auto_now_add=True, verbose_name='последние изменения')),
            ],
            options={
                'verbose_name': 'письмо',
                'verbose_name_plural': 'письма',
            },
        ),
    ]
