# Generated by Django 4.2 on 2024-05-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='body',
            field=models.CharField(blank=True, null=True, verbose_name='письмо'),
        ),
    ]
