# Generated by Django 4.2 on 2024-05-12 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mailing', '0001_initial'),
        ('logmail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logmail',
            name='settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailing.mailingletters', verbose_name='настройки'),
        ),
    ]
